### SUCCESSFUL REQUEST
POST http://localhost:5168/users
Content-Type: application/json

{
    "firstName": "Luis",
    "lastName": "Doe",
    "userName": "johndoe",
    "email": "johndoe@gmai.com",
    "phoneNumber": "+1234567890",
    "password": "password",
    "hasConsented": true
}

### BAD PWD REQUEST
POST http://localhost:5168/users
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "userName": "johndoe",
    "email": "johndoe@gmai.com",
    "password": "pass",
    "phoneNumber": "+1234567890",
    "hasConsented": true
}

### BAD PHONE REQUEST
POST http://localhost:5168/users
Content-Type: application/json


{
    "firstName": "John",
    "lastName": "Doe",
    "userName": "johndoe",
    "email": "johndoe@gmai.com",
    "password": "password",
    "phoneNumber": "1234567890",
    "hasConsented": true
}

### UNAUTHORIZED REQUEST USER HAS NOT CONSENTED
POST http://localhost:5168/users
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "userName": "johndoe",
    "email": "johndoe@gmail.com",
    "password": "password",
    "phoneNumber": "+1234567890",
    "hasConsented": false
}